In [1]:
import numpy as np
import pandas as pd
import streamlit as st 

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_predict
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, roc_curve, roc_auc_score, accuracy_score

In [2]:
df = pd.read_csv('emails.csv')
df.head()

                                                text  spam
0  Subject: naturally irresistible your corporate...     1
1  Subject: the stock trading gunslinger  fanny i...     1
2  Subject: unbelievable new homes made easy  im ...     1
3  Subject: 4 color printing special  request add...     1
4  Subject: do not have money , get software cds ...     1

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5728 entries, 0 to 5727
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   text    5728 non-null   str
 1   spam    5728 non-null   int64
dtypes: int64(1), str(1)
memory usage: 8.6 MB

In [4]:
df['spam'].value_counts()

spam
0    4360
1    1368
Name: count, dtype: int64

In [5]:
df['text'][0]

"Subject: naturally irresistible your corporate identity  lt is really hard to recollect a company : the  market is full of suqgestions and the information isoverwhelminq ; but a good  catchy logo , stylish statlonery and outstanding website  will make the task much easier .  we do not promise that havinq ordered a iogo your  company will automaticaily become a world ieader : it isguite ciear that  without good products , effective business organization and practicable aim it  will be hotat nowadays market ; but we do promise that your marketing efforts  will become much more effective . here is the list of clear  benefits : creativeness : hand - made , original logos , specially done  to reflect your distinctive company image . convenience : logo and stationery  are provided in all formats ; easy - to - use content management system letsyou  change your website content and even its structure . promptness : you  will see logo drafts within three business days . affordability : your  marketing break - through shouldn ' t make gaps in your budget . 100 % satisfaction  guaranteed : we provide unlimited amount of changes with no extra fees for you to  be surethat you will love the result of this collaboration . have a look at our  portfolio _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ not interested . . . _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _"

import nltk

from nltk.corpus import stopwords

nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

stop_words

In [6]:
df['text'][0].split()

['Subject:',
 'naturally',
 'irresistible',
 'your',
 'corporate',
 'identity',
 'lt',
 'is',
 'really',
 'hard',
 'to',
 'recollect',
 'a',
 'company',
 ':',
 'the',
 'market',
 'is',
 'full',
 'of',
 'suqgestions',
 'and',
 'the',
 'information',
 'isoverwhelminq',
 ';',
 'but',
 'a',
 'good',
 'catchy',
 'logo',
 ',',
 'stylish',
 'statlonery',
 'and',
 'outstanding',
 'website',
 'will',
 'make',
 'the',
 'task',
 'much',
 'easier',
 '.',
 'we',
 'do',
 'not',
 'promise',
 'that',
 'havinq',
 'ordered',
 'a',
 'iogo',
 'your',
 'company',
 'will',
 'automaticaily',
 'become',
 'a',
 'world',
 'ieader',
 ':',
 'it',
 'isguite',
 'ciear',
 'that',
 'without',
 'good',
 'products',
 ',',
 'effective',
 'business',
 'organization',
 'and',
 'practicable',
 'aim',
 'it',
 'will',
 'be',
 'hotat',
 'nowadays',
 'market',
 ';',
 'but',
 'we',
 'do',
 'promise',
 'that',
 'your',
 'marketing',
 'efforts',
 'will',
 'become',
 'much',
 'more',
 'effective',
 '.',
 'here',
 'is',
 'the',
 'list',
 'of',
 'clear',
 'benefits',
 ':',
 'creativeness',
 ':',
 'hand',
 '-',
 'made',
 ',',
 'original',
 'logos',
 ',',
 'specially',
 'done',
 'to',
 'reflect',
 'your',
 'distinctive',
 'company',
 'image',
 '.',
 'convenience',
 ':',
 'logo',
 'and',
 'stationery',
 'are',
 'provided',
 'in',
 'all',
 'formats',
 ';',
 'easy',
 '-',
 'to',
 '-',
 'use',
 'content',
 'management',
 'system',
 'letsyou',
 'change',
 'your',
 'website',
 'content',
 'and',
 'even',
 'its',
 'structure',
 '.',
 'promptness',
 ':',
 'you',
 'will',
 'see',
 'logo',
 'drafts',
 'within',
 'three',
 'business',
 'days',
 '.',
 'affordability',
 ':',
 'your',
 'marketing',
 'break',
 '-',
 'through',
 'shouldn',
 "'",
 't',
 'make',
 'gaps',
 'in',
 'your',
 'budget',
 '.',
 '100',
 '%',
 'satisfaction',
 'guaranteed',
 ':',
 'we',
 'provide',
 'unlimited',
 'amount',
 'of',
 'changes',
 'with',
 'no',
 'extra',
 'fees',
 'for',
 'you',
 'to',
 'be',
 'surethat',
 'you',
 'will',
 'love',
 'the',
 'result',
 'of',
 'this',
 'collaboration',
 '.',
 'have',
 'a',
 'look',
 'at',
 'our',
 'portfolio',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 'not',
 'interested',
 '.',
 '.',
 '.',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_',
 '_']

In [7]:
import nltk

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Electronica
[nltk_data]     Care\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [8]:
from nltk.corpus import stopwords

# 1. عرف المتغير الأول وتحقق من اللغة (arabic أو english)
stop_words = stopwords.words('arabic')


# 2. بعدين عرف الدالة
def remove_stop_words(text):
  words = text.split()
  words = [word for word in words if word not in stop_words]
  return ' '.join(words)


# 3. طبقها على الداتا فريم
df['new_text'] = df['text'].apply(remove_stop_words)

In [9]:
spam_words = " ".join(df[df['spam'] == 1]['new_text']).lower().split()
ham_words = " ".join(df[df['spam'] == 0]['new_text']).lower().split()

In [10]:
from collections import Counter

spam_counter = Counter(spam_words)
ham_counter = Counter(ham_words)    
spam_counter.most_common(100)

[('.', 19839),
 ('_', 13556),
 (',', 11514),
 ('the', 8975),
 ('-', 8514),
 ('to', 8165),
 ('and', 6517),
 ('of', 5629),
 ('you', 4920),
 ('a', 4695),
 (':', 4691),
 ('in', 3879),
 ('your', 3730),
 ('!', 3310),
 ('for', 3186),
 ('is', 2977),
 ('this', 2822),
 ('/', 2578),
 ("'", 2326),
 ('$', 2242),
 ('that', 1896),
 ('i', 1772),
 ('with', 1734),
 ('we', 1724),
 ('be', 1675),
 ('"', 1655),
 (')', 1598),
 ('are', 1590),
 ('or', 1588),
 ('it', 1584),
 ('on', 1582),
 ('(', 1514),
 ('from', 1471),
 ('will', 1429),
 ('our', 1404),
 ('not', 1382),
 ('subject:', 1368),
 ('have', 1352),
 ('s', 1333),
 ('*', 1300),
 ('as', 1201),
 ('=', 1182),
 ('by', 1038),
 ('com', 998),
 ('at', 988),
 ('?', 981),
 ('all', 979),
 ('1', 952),
 ('if', 869),
 ('business', 844),
 ('can', 830),
 ('company', 805),
 ('email', 804),
 ('an', 790),
 ('|', 789),
 ('here', 770),
 ('do', 767),
 ('information', 740),
 ('more', 727),
 ('my', 699),
 ('e', 698),
 ('no', 688),
 ('5', 687),
 ('money', 662),
 ('%', 659),
 ('2', 613),
 ('free', 606),
 ('3', 604),
 ('http', 600),
 ('any', 592),
 ('get', 590),
 ('has', 589),
 (';', 588),
 ('mail', 586),
 ('one', 581),
 ('please', 581),
 ('t', 576),
 ('now', 575),
 ('@', 575),
 ('out', 566),
 ('000', 560),
 ('us', 537),
 ('click', 531),
 ('just', 524),
 ('time', 521),
 ('new', 504),
 ('make', 496),
 ('may', 489),
 ('only', 474),
 ('website', 465),
 ('adobe', 462),
 ('was', 451),
 ('over', 450),
 ('0', 450),
 ('but', 449),
 ('software', 438),
 ('www', 426),
 ('#', 426),
 ('about', 423),
 ('message', 418)]

In [11]:
ham_counter.most_common(100)

[('-', 96708),
 ('.', 72655),
 (',', 49629),
 ('the', 41135),
 ('/', 37733),
 (':', 37679),
 ('to', 33571),
 ('>', 21997),
 ('and', 20961),
 ('of', 18128),
 ('i', 15649),
 ('a', 15250),
 ('you', 14234),
 ('in', 14096),
 ('@', 13976),
 ('for', 13510),
 ('enron', 13382),
 ('ect', 11417),
 ('on', 11137),
 ('is', 9618),
 (')', 8988),
 ('vince', 8531),
 ("'", 8483),
 ('?', 8446),
 ('(', 8264),
 ('be', 7587),
 ('that', 7395),
 ('"', 7275),
 ('this', 7209),
 ('with', 7119),
 ('we', 6964),
 ('will', 6698),
 ('*', 6490),
 ('have', 6204),
 ('at', 5894),
 ('hou', 5569),
 ('your', 5544),
 ('from', 5275),
 ('s', 5173),
 ('it', 5104),
 ('as', 4974),
 ('2000', 4935),
 ('are', 4931),
 ('am', 4826),
 ('kaminski', 4770),
 ('by', 4474),
 ('com', 4444),
 ('please', 4386),
 ('subject:', 4360),
 ('if', 4324),
 ('subject', 4245),
 ('would', 4151),
 ('me', 3996),
 ('cc', 3889),
 ('re', 3825),
 ('j', 3693),
 ('_', 3678),
 ('or', 3630),
 ('can', 3425),
 ('pm', 3262),
 ('not', 3193),
 ('my', 3061),
 ('2001', 3060),
 ('our', 2943),
 ('an', 2913),
 ('research', 2670),
 ('thanks', 2523),
 ('1', 2490),
 ('2', 2323),
 ('know', 2297),
 ('group', 2255),
 ('any', 2230),
 ('10', 2213),
 ('time', 2212),
 ('energy', 2115),
 ('has', 2091),
 ('he', 2086),
 ('=', 2067),
 ('risk', 1984),
 ('may', 1974),
 ('about', 1971),
 ('all', 1950),
 ('power', 1916),
 (';', 1914),
 ('!', 1865),
 ('was', 1841),
 ('3', 1838),
 ('do', 1837),
 ('let', 1822),
 ('like', 1795),
 ('new', 1776),
 ('meeting', 1772),
 ('00', 1680),
 ('shirley', 1679),
 ('01', 1673),
 ('11', 1661),
 ('corp', 1643),
 ('but', 1638),
 ('edu', 1620),
 ('also', 1604)]

Preprocessing

In [12]:
df.duplicated().sum()

np.int64(33)

In [13]:
df['text'].duplicated().sum()

np.int64(33)

In [14]:
df.drop_duplicates(inplace=True,ignore_index=True)

In [15]:
df.isna().sum().max()

np.int64(0)

In [16]:
X = df['text']
y = df['spam']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((4556,), (1139,), (4556,), (1139,))

In [17]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

vectorizer = TfidfVectorizer(lowercase=True, stop_words='english', analyzer='word',ngram_range=(1,2),min_df=5,max_df=0.8,sublinear_tf=True)
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

In [18]:
X_train_vectorized_df = pd.DataFrame(X_train_vectorized.toarray(), columns=vectorizer.get_feature_names_out())
X_train_vectorized_df.describe()

,00,00 00,00 01,00 02,00 03,00 04,00 05,00 0500,00 06,00 0600,...,zip code,zip postal,ziplip,ziplip com,zipped,zipter,zipter oct,zipter rudi,zone,zzzz
count,4556.000000,4556.000000,4556.000000,4556.000000,4556.000000,4556.000000,4556.000000,4556.000000,4556.000000,4556.000000,...,4556.000000,4556.000000,4556.000000,4556.000000,4556.000000,4556.000000,4556.000000,4556.000000,4556.000000,4556.000000
mean,0.009140,0.001060,0.000294,0.000204,0.000144,0.000145,0.000124,0.000286,0.000161,0.000228,...,0.000177,0.000126,0.000564,0.000564,0.000102,0.000404,0.000123,0.000091,0.000238,0.000204
std,0.025166,0.010331,0.004788,0.004264,0.003685,0.003824,0.003076,0.004973,0.004059,0.004121,...,0.004594,0.003394,0.008096,0.008096,0.003127,0.005596,0.002637,0.002517,0.006343,0.006841
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,0.223288,0.246090,0.104338,0.111737,0.144555,0.135687,0.101131,0.135956,0.138986,0.119115,...,0.135933,0.122948,0.177818,0.177818,0.117087,0.130096,0.062051,0.074497,0.211951,0.341464

Modeling

In [19]:
log_reg = LogisticRegression(C=1, max_iter=1000, random_state=42,class_weight='balanced')
log_reg.fit(X_train_vectorized, y_train)

LogisticRegression(C=1, class_weight='balanced', max_iter=1000, random_state=42)

In [20]:
y_valid_pred = cross_val_predict(log_reg, X_train_vectorized, y_train, cv=3, method='predict', n_jobs=-1)


print("Train Accuracy:", log_reg.score(X_train_vectorized, y_train))
print("Validation Accuracy:", accuracy_score(y_train, y_valid_pred))    
print('Precision:', precision_score(y_train, y_valid_pred))
print('Recall:', recall_score(y_train, y_valid_pred))
print('F1 Score:', f1_score(y_train, y_valid_pred))
confusion_matrix(y_train, y_valid_pred)

Train Accuracy: 0.9958296751536435
Validation Accuracy: 0.9883669885864794
Precision: 0.9610274579273693
Recall: 0.9917733089579525
F1 Score: 0.9761583445793972

array([[3418,   44],
       [   9, 1085]])

In [21]:
svm_model = LinearSVC(class_weight='balanced', random_state=42)

In [22]:
svm_model.fit(X_train_vectorized, y_train)

LinearSVC(class_weight='balanced', random_state=42)

In [23]:
y_valid_pred_svm = cross_val_predict(svm_model,X_train_vectorized, y_train, cv=3, method='predict', n_jobs=-1)

In [24]:
print("SVM Results")
print("Train Accuracy:", svm_model.score(X_train_vectorized, y_train))
print("Validation Accuracy:", accuracy_score(y_train, y_valid_pred_svm))
print("Precision:", precision_score(y_train, y_valid_pred_svm))
print("Recall:", recall_score(y_train, y_valid_pred_svm))
print("F1 Score:", f1_score(y_train, y_valid_pred_svm))
print("Confusion Matrix:")
print(confusion_matrix(y_train, y_valid_pred_svm))

SVM Results
Train Accuracy: 0.9995610184372257
Validation Accuracy: 0.992756804214223
Precision: 0.9880404783808647
Recall: 0.9817184643510055
F1 Score: 0.984869325997249
Confusion Matrix:
[[3449   13]
 [  20 1074]]

In [25]:
from sklearn.naive_bayes import MultinomialNB
nb_model = MultinomialNB()
nb_model.fit(X_train_vectorized, y_train)

MultinomialNB()

In [26]:
y_valid_pred_nb = cross_val_predict(nb_model,X_train_vectorized,y_train,cv=3,method='predict',n_jobs=-1)

In [27]:
print("Naive Bayes Results")
print("Train Accuracy:", nb_model.score(X_train_vectorized, y_train))
print("Validation Accuracy:", accuracy_score(y_train, y_valid_pred_nb))
print("Precision:", precision_score(y_train, y_valid_pred_nb))
print("Recall:", recall_score(y_train, y_valid_pred_nb))
print("F1 Score:", f1_score(y_train, y_valid_pred_nb))
print("Confusion Matrix:")
print(confusion_matrix(y_train, y_valid_pred_nb))

Naive Bayes Results
Train Accuracy: 0.9866110623353819
Validation Accuracy: 0.9620280948200176
Precision: 0.9989165763813651
Recall: 0.8427787934186471
F1 Score: 0.9142290530490828
Confusion Matrix:
[[3461    1]
 [ 172  922]]

In [28]:
results = pd.DataFrame({
    'Model': ['Logistic Regression', 'SVM', 'Naive Bayes'],
    'Accuracy': [
        accuracy_score(y_train, y_valid_pred),
        accuracy_score(y_train, y_valid_pred_svm),
        accuracy_score(y_train, y_valid_pred_nb)
    ],
    'Precision': [
        precision_score(y_train, y_valid_pred),
        precision_score(y_train, y_valid_pred_svm),
        precision_score(y_train, y_valid_pred_nb)
    ],
    'Recall': [
        recall_score(y_train, y_valid_pred),
        recall_score(y_train, y_valid_pred_svm),
        recall_score(y_train, y_valid_pred_nb)
    ],
    'F1 Score': [
        f1_score(y_train, y_valid_pred),
        f1_score(y_train, y_valid_pred_svm),
        f1_score(y_train, y_valid_pred_nb)
    ]
})

results

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.988367   0.961027  0.991773  0.976158
1                  SVM  0.992757   0.988040  0.981718  0.984869
2          Naive Bayes  0.962028   0.998917  0.842779  0.914229

In [29]:
plt.figure(figsize=(8,5))
sns.barplot(data=results, x='Model', y='F1 Score')
plt.title('Model Comparison Based on F1 Score')
plt.ylim(0, 1)
plt.show()

C:\Users\Electronica Care\AppData\Local\Temp\ipykernel_17568\2768145143.py:5: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()

In [30]:
from sklearn.metrics import classification_report

y_test_pred_svm = svm_model.predict(X_test_vectorized)

print("Final Test Results - SVM")
print("Test Accuracy:", accuracy_score(y_test, y_test_pred_svm))
print("Precision:", precision_score(y_test, y_test_pred_svm))
print("Recall:", recall_score(y_test, y_test_pred_svm))
print("F1 Score:", f1_score(y_test, y_test_pred_svm))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_test_pred_svm))
print("Classification Report:")
print(classification_report(y_test, y_test_pred_svm))

Final Test Results - SVM
Test Accuracy: 0.9956101843722563
Precision: 0.9890909090909091
Recall: 0.9927007299270073
F1 Score: 0.9908925318761385
Confusion Matrix:
[[862   3]
 [  2 272]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       865
           1       0.99      0.99      0.99       274

    accuracy                           1.00      1139
   macro avg       0.99      0.99      0.99      1139
weighted avg       1.00      1.00      1.00      1139

In [31]:
message = ["Congratulations! You have won a free prize, click here now"]

message_vectorized = vectorizer.transform(message)

prediction = svm_model.predict(message_vectorized)

if prediction[0] == 1:
    print("Spam Email")
else:
    print("Not Spam Email")

Spam Email

In [32]:
message = ["Hi, I hope you are doing well. Please find the meeting schedule attached."]

message_vectorized = vectorizer.transform(message)

prediction = svm_model.predict(message_vectorized)

if prediction[0] == 1:
    print("Spam Email")
else:
    print("Not Spam Email")

Not Spam Email

In [33]:
import pickle

In [34]:
pickle.dump(svm_model, open('spam_model.pkl', 'wb'))

pickle.dump(vectorizer, open('vectorizer.pkl', 'wb'))